import type { MetadataRoute } from 'next';

/**
 * Robots.txt configuration
 * Automatically generated by Next.js at /robots.txt
 */
export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: '*',
        allow: '/',
        disallow: ['/api/'],
      },
    ],
    sitemap: 'https://tpmjs.com/sitemap.xml',
  };
}
