import type { MetadataRoute } from 'next';

/**
 * Robots.txt configuration
 * Automatically generated by Next.js at /robots.txt
 */
export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: '*',
        allow: '/',
        disallow: [
          '/api/',
          '/dashboard',
          '/dashboard/*',
          '/admin',
          '/sign-in',
          '/sign-up',
          '/forgot-password',
          '/reset-password',
          '/verify-email',
          '/cli/auth',
          '/omega',
          '/style-guide',
          '/health',
        ],
      },
    ],
    sitemap: 'https://tpmjs.com/sitemap.xml',
  };
}
