import { prisma } from '@tpmjs/db';
import type { MetadataRoute } from 'next';
import { defaultToolDiscoveryFilter } from '~/lib/tool-health-policy';

// Force dynamic rendering to avoid database calls during build
export const dynamic = 'force-dynamic';

/**
 * Dynamic sitemap that includes all pages and tools from the database
 * Automatically generated by Next.js at /sitemap.xml
 */
export default async function sitemap(): Promise<MetadataRoute.Sitemap> {
  const baseUrl = 'https://tpmjs.com';

  const now = new Date();

  // Static pages — comprehensive list of all public routes
  const staticPages: MetadataRoute.Sitemap = [
    // Core
    { url: baseUrl, lastModified: now, changeFrequency: 'daily', priority: 1 },
    { url: `${baseUrl}/tools`, lastModified: now, changeFrequency: 'daily', priority: 0.9 },
    {
      url: `${baseUrl}/tool/tool-search`,
      lastModified: now,
      changeFrequency: 'daily',
      priority: 0.9,
    },
    { url: `${baseUrl}/collections`, lastModified: now, changeFrequency: 'daily', priority: 0.8 },
    { url: `${baseUrl}/agents`, lastModified: now, changeFrequency: 'daily', priority: 0.8 },
    { url: `${baseUrl}/trending`, lastModified: now, changeFrequency: 'hourly', priority: 0.8 },
    { url: `${baseUrl}/scenarios`, lastModified: now, changeFrequency: 'daily', priority: 0.7 },

    // Getting started & publishing
    {
      url: `${baseUrl}/getting-started`,
      lastModified: now,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    { url: `${baseUrl}/publish`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/setup`, lastModified: now, changeFrequency: 'monthly', priority: 0.7 },

    // Docs
    { url: `${baseUrl}/docs`, lastModified: now, changeFrequency: 'weekly', priority: 0.8 },
    {
      url: `${baseUrl}/docs/quickstart`,
      lastModified: now,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    { url: `${baseUrl}/docs/api`, lastModified: now, changeFrequency: 'weekly', priority: 0.7 },
    { url: `${baseUrl}/docs/sdk`, lastModified: now, changeFrequency: 'weekly', priority: 0.7 },
    { url: `${baseUrl}/docs/cli`, lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${baseUrl}/docs/agents`, lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    {
      url: `${baseUrl}/docs/executors`,
      lastModified: now,
      changeFrequency: 'monthly',
      priority: 0.6,
    },
    {
      url: `${baseUrl}/docs/sharing`,
      lastModified: now,
      changeFrequency: 'monthly',
      priority: 0.6,
    },
    { url: `${baseUrl}/docs/skills`, lastModified: now, changeFrequency: 'monthly', priority: 0.6 },
    {
      url: `${baseUrl}/docs/scenarios`,
      lastModified: now,
      changeFrequency: 'monthly',
      priority: 0.6,
    },
    {
      url: `${baseUrl}/docs/tutorials`,
      lastModified: now,
      changeFrequency: 'monthly',
      priority: 0.6,
    },
    {
      url: `${baseUrl}/docs/tutorials/mcp`,
      lastModified: now,
      changeFrequency: 'monthly',
      priority: 0.7,
    },
    {
      url: `${baseUrl}/docs/tutorials/agents`,
      lastModified: now,
      changeFrequency: 'monthly',
      priority: 0.6,
    },
    {
      url: `${baseUrl}/docs/architecture`,
      lastModified: now,
      changeFrequency: 'monthly',
      priority: 0.5,
    },

    // Product / reference
    { url: `${baseUrl}/spec`, lastModified: now, changeFrequency: 'weekly', priority: 0.7 },
    { url: `${baseUrl}/sdk`, lastModified: now, changeFrequency: 'weekly', priority: 0.7 },
    {
      url: `${baseUrl}/integrations`,
      lastModified: now,
      changeFrequency: 'monthly',
      priority: 0.7,
    },
    { url: `${baseUrl}/playground`, lastModified: now, changeFrequency: 'weekly', priority: 0.6 },
    { url: `${baseUrl}/use-cases`, lastModified: now, changeFrequency: 'weekly', priority: 0.6 },

    // Resources
    {
      url: `${baseUrl}/how-it-works`,
      lastModified: now,
      changeFrequency: 'monthly',
      priority: 0.7,
    },
    { url: `${baseUrl}/compare`, lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${baseUrl}/faq`, lastModified: now, changeFrequency: 'monthly', priority: 0.6 },
    { url: `${baseUrl}/about`, lastModified: now, changeFrequency: 'monthly', priority: 0.6 },
    { url: `${baseUrl}/changelog`, lastModified: now, changeFrequency: 'weekly', priority: 0.6 },
    { url: `${baseUrl}/features`, lastModified: now, changeFrequency: 'monthly', priority: 0.6 },
    { url: `${baseUrl}/stats`, lastModified: now, changeFrequency: 'daily', priority: 0.5 },

    // Legal
    { url: `${baseUrl}/privacy`, lastModified: now, changeFrequency: 'yearly', priority: 0.3 },
    { url: `${baseUrl}/terms`, lastModified: now, changeFrequency: 'yearly', priority: 0.3 },
  ];

  let categoryPages: MetadataRoute.Sitemap = [];

  try {
    // One crawlable browse URL per category facet (small, ~31 entries).
    const categories = await prisma.package.findMany({
      distinct: ['category'],
      select: { category: true },
      orderBy: { category: 'asc' },
    });
    categoryPages = categories
      .map((row) => row.category)
      .filter((category): category is string => Boolean(category))
      .map((category) => ({
        url: `${baseUrl}/tools?category=${encodeURIComponent(category)}`,
        lastModified: now,
        changeFrequency: 'daily' as const,
        priority: 0.6,
      }));
  } catch (error) {
    console.error('sitemap: failed to fetch categories from DB, skipping category pages', error);
  }

  let toolPages: MetadataRoute.Sitemap = [];

  try {
    const tools = await prisma.tool.findMany({
      where: defaultToolDiscoveryFilter(),
      select: {
        package: {
          select: {
            npmPackageName: true,
            updatedAt: true,
          },
        },
        name: true,
        updatedAt: true,
      },
      orderBy: {
        updatedAt: 'desc',
      },
    });

    toolPages = tools.map((tool) => {
      const lastModified =
        tool.updatedAt > tool.package.updatedAt ? tool.updatedAt : tool.package.updatedAt;

      return {
        url: `${baseUrl}/tool/${tool.package.npmPackageName}/${tool.name}`,
        lastModified,
        changeFrequency: 'weekly' as const,
        priority: 0.7,
      };
    });
  } catch (error) {
    console.error('sitemap: failed to fetch tools from DB, returning static pages only', error);
  }

  return [...staticPages, ...categoryPages, ...toolPages];
}
