export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';
export const maxDuration = 60;

/**
 * GET /api/setup/install.sh
 *
 * Serves the TPMJS install script. Two modes:
 *   1. curl -fsSL https://tpmjs.com/install.sh | bash
 *      → Opens browser, polls for setup completion
 *   2. curl -fsSL https://tpmjs.com/install.sh | bash -s -- --token=<token>
 *      → Direct token redemption (skip browser)
 */
export async function GET() {
  // Using an array of lines to avoid template literal escaping issues with bash $ variables
  const lines = [
    '#!/bin/bash',
    'set -euo pipefail',
    '',
    '# Colors',
    "RED=$'\\033[0;31m'",
    "GREEN=$'\\033[0;32m'",
    "YELLOW=$'\\033[1;33m'",
    "BLUE=$'\\033[0;34m'",
    "CYAN=$'\\033[0;36m'",
    "BOLD=$'\\033[1m'",
    "NC=$'\\033[0m'",
    '',
    'info()    { printf "%s[info]%s  %s\\n" "$BLUE" "$NC" "$1"; }',
    'success() { printf "%s[ok]%s    %s\\n" "$GREEN" "$NC" "$1"; }',
    'warn()    { printf "%s[warn]%s  %s\\n" "$YELLOW" "$NC" "$1"; }',
    'fail()    { printf "%s[error]%s %s\\n" "$RED" "$NC" "$1"; }',
    '',
    '# Banner',
    'printf "\\n%s%s" "$BOLD" "$CYAN"',
    'printf "  _____ ____  __  __     _ ____  \\n"',
    'printf " |_   _|  _ \\\\|  \\\\/  |   | / ___| \\n"',
    'printf "   | | | |_) | |\\\\/| |_  | \\\\___ \\\\ \\n"',
    'printf "   | | |  __/| |  | | |_| |___) |\\n"',
    'printf "   |_| |_|   |_|  |_|\\\\___/|____/ \\n"',
    'printf "\\n"',
    'printf "  MCP Server Setup%s\\n\\n" "$NC"',
    '',
    '# Pre-flight checks',
    'if ! command -v curl &>/dev/null; then',
    '  fail "curl is required but not installed."',
    '  exit 1',
    'fi',
    '',
    'if ! command -v node &>/dev/null; then',
    '  fail "Node.js is required but not installed."',
    '  printf "  Install it from https://nodejs.org\\n"',
    '  exit 1',
    'fi',
    '',
    '# Parse arguments',
    'TOKEN=""',
    'for arg in "$@"; do',
    '  case "$arg" in',
    '    --token=*)',
    '      TOKEN="${arg#--token=}"',
    '      ;;',
    '  esac',
    'done',
    '',
    '# ---- Open browser flow (no token) ----------------------------------------',
    '',
    'if [ -z "$TOKEN" ]; then',
    '  info "Opening your browser to configure TPMJS..."',
    '  printf "\\n"',
    '',
    '  CLAIM_RESPONSE=$(curl -fsSL -X POST "https://tpmjs.com/api/setup/claim" 2>&1) || {',
    '    fail "Failed to connect to tpmjs.com"',
    '    exit 1',
    '  }',
    '',
    '  CLAIM_CODE=$(node -e "console.log(JSON.parse(process.argv[1]).claimCode)" "$CLAIM_RESPONSE" 2>/dev/null) || {',
    '    fail "Failed to parse response"',
    '    exit 1',
    '  }',
    '',
    '  SETUP_URL="https://tpmjs.com/setup?claim=${CLAIM_CODE}"',
    '',
    '  # Open browser',
    '  if command -v open &>/dev/null; then',
    '    open "$SETUP_URL"',
    '  elif command -v xdg-open &>/dev/null; then',
    '    xdg-open "$SETUP_URL"',
    '  elif command -v wslview &>/dev/null; then',
    '    wslview "$SETUP_URL"',
    '  else',
    '    printf "  Open this URL in your browser:\\n"',
    '    printf "  %s%s%s\\n" "$BOLD" "$SETUP_URL" "$NC"',
    '  fi',
    '',
    '  printf "  %s->%s Sign in and select your collections + editors\\n" "$CYAN" "$NC"',
    '  printf "  %s->%s Click %sGenerate Install Command%s when ready\\n" "$CYAN" "$NC" "$BOLD" "$NC"',
    '  printf "\\n"',
    '  info "Waiting for you to complete setup in the browser..."',
    '',
    '  # Poll for completion (5 min timeout, 2 sec interval)',
    '  TIMEOUT=300',
    '  ELAPSED=0',
    '  POLL_DATA=""',
    '',
    '  while [ "$ELAPSED" -lt "$TIMEOUT" ]; do',
    '    POLL_RESPONSE=$(curl -fsSL "https://tpmjs.com/api/setup/poll/${CLAIM_CODE}" 2>/dev/null) || true',
    '',
    '    POLL_STATUS=$(node -e "',
    '      try {',
    '        const d = JSON.parse(process.argv[1]);',
    "        console.log(d.status || 'error');",
    "      } catch { console.log('error'); }",
    '    " "$POLL_RESPONSE" 2>/dev/null) || POLL_STATUS="error"',
    '',
    '    if [ "$POLL_STATUS" = "ready" ]; then',
    '      POLL_DATA="$POLL_RESPONSE"',
    '      break',
    '    fi',
    '',
    '    if [ "$POLL_STATUS" = "error" ]; then',
    '      ERROR_MSG=$(node -e "',
    "        try { console.log(JSON.parse(process.argv[1]).error || 'Unknown error'); }",
    "        catch { console.log('Unknown error'); }",
    '      " "$POLL_RESPONSE" 2>/dev/null) || ERROR_MSG="Unknown error"',
    '      fail "$ERROR_MSG"',
    '      exit 1',
    '    fi',
    '',
    '    sleep 2',
    '    ELAPSED=$((ELAPSED + 2))',
    '',
    '    if [ $((ELAPSED % 10)) -eq 0 ]; then',
    '      printf "  %s...still waiting (%ss)%s\\n" "$BLUE" "$ELAPSED" "$NC"',
    '    fi',
    '  done',
    '',
    '  if [ -z "$POLL_DATA" ]; then',
    '    fail "Timed out waiting for setup (5 minutes)."',
    '    printf "  Run the script again to retry.\\n"',
    '    exit 1',
    '  fi',
    '',
    '  printf "\\n"',
    '  success "Configuration received!"',
    '  printf "\\n"',
    '',
    '  USERNAME=$(node -e "console.log(JSON.parse(process.argv[1]).username)" "$POLL_DATA")',
    '  API_KEY=$(node -e "const d=JSON.parse(process.argv[1]); console.log(d.apiKey||\'\')" "$POLL_DATA")',
    '  MAPPING_COUNT=$(node -e "console.log(JSON.parse(process.argv[1]).mappings.length)" "$POLL_DATA")',
    '  PARSED="$POLL_DATA"',
    '',
    'else',
    '  # ---- Direct token flow ---------------------------------------------------',
    '  info "Redeeming setup token..."',
    '',
    '  RESPONSE=$(curl -fsSL "https://tpmjs.com/api/setup/redeem/$TOKEN" 2>&1) || {',
    '    fail "Failed to redeem token. It may be expired or already used."',
    '    printf "  Run: curl -fsSL https://tpmjs.com/install.sh | bash\\n"',
    '    exit 1',
    '  }',
    '',
    '  node -e "',
    '    const data = JSON.parse(process.argv[1]);',
    '    if (!data.success) {',
    "      console.error(data.error || 'Unknown error');",
    '      process.exit(1);',
    '    }',
    '  " "$RESPONSE" 2>&1 || {',
    '    fail "Failed to parse server response."',
    '    exit 1',
    '  }',
    '',
    '  PARSED="$RESPONSE"',
    '  USERNAME=$(node -e "console.log(JSON.parse(process.argv[1]).username)" "$PARSED")',
    '  API_KEY=$(node -e "const d=JSON.parse(process.argv[1]); console.log(d.apiKey||\'\')" "$PARSED")',
    '  MAPPING_COUNT=$(node -e "console.log(JSON.parse(process.argv[1]).mappings.length)" "$PARSED")',
    'fi',
    '',
    'success "Authenticated as ${BOLD}${USERNAME}${NC}"',
    '',
    'if [ -n "$API_KEY" ]; then',
    '  info "API key: ${API_KEY:0:20}..."',
    'fi',
    '',
    'printf "\\n"',
    '',
    '# ---- Configure editors ----------------------------------------------------',
    '',
    'CONFIGURED=0',
    'FAILED=0',
    '',
    'for i in $(seq 0 $((MAPPING_COUNT - 1))); do',
    '  SLUG=$(node -e "console.log(JSON.parse(process.argv[1]).mappings[$i].collectionSlug)" "$PARSED")',
    '  NAME=$(node -e "console.log(JSON.parse(process.argv[1]).mappings[$i].collectionName)" "$PARSED")',
    '  EDITOR=$(node -e "console.log(JSON.parse(process.argv[1]).mappings[$i].editor)" "$PARSED")',
    '  MCP_URL=$(node -e "console.log(JSON.parse(process.argv[1]).mappings[$i].mcpUrl)" "$PARSED")',
    '  SERVER_NAME="tpmjs-$SLUG"',
    '',
    '  info "Configuring ${BOLD}${NAME}${NC} -> ${BOLD}${EDITOR}${NC}..."',
    '',
    '  case "$EDITOR" in',
    '    claude-code)',
    '      if ! command -v claude &>/dev/null; then',
    '        warn "claude CLI not found. Skipping $NAME for Claude Code."',
    '        warn "  Install: npm install -g @anthropic-ai/claude-code"',
    '        FAILED=$((FAILED + 1))',
    '        continue',
    '      fi',
    '',
    '      MCP_JSON=$(node -e "',
    "        const config = { type: 'http', url: process.argv[1] };",
    "        if (process.argv[2]) config.headers = { Authorization: 'Bearer ' + process.argv[2] };",
    '        console.log(JSON.stringify(config));',
    '      " "$MCP_URL" "$API_KEY")',
    '',
    '      if claude mcp add-json "$SERVER_NAME" "$MCP_JSON" 2>/dev/null; then',
    '        success "$NAME -> Claude Code"',
    '        CONFIGURED=$((CONFIGURED + 1))',
    '      else',
    '        warn "Failed to configure $NAME for Claude Code"',
    '        FAILED=$((FAILED + 1))',
    '      fi',
    '      ;;',
    '',
    '    cursor)',
    '      CONFIG_PATH="$HOME/.cursor/mcp.json"',
    '      node -e "',
    "        const fs = require('fs');",
    "        const path = require('path');",
    '        const configPath = process.argv[1];',
    '        const serverName = process.argv[2];',
    '        const mcpUrl = process.argv[3];',
    '        const apiKey = process.argv[4];',
    '        let config = {};',
    "        try { config = JSON.parse(fs.readFileSync(configPath, 'utf8')); } catch {}",
    '        if (!config.mcpServers) config.mcpServers = {};',
    "        const server = { type: 'http', url: mcpUrl };",
    "        if (apiKey) server.headers = { Authorization: 'Bearer ' + apiKey };",
    '        config.mcpServers[serverName] = server;',
    '        fs.mkdirSync(path.dirname(configPath), { recursive: true });',
    '        fs.writeFileSync(configPath, JSON.stringify(config, null, 2));',
    '      " "$CONFIG_PATH" "$SERVER_NAME" "$MCP_URL" "$API_KEY" && {',
    '        success "$NAME -> Cursor"',
    '        CONFIGURED=$((CONFIGURED + 1))',
    '      } || {',
    '        warn "Failed to configure $NAME for Cursor"',
    '        FAILED=$((FAILED + 1))',
    '      }',
    '      ;;',
    '',
    '    windsurf)',
    '      CONFIG_PATH="$HOME/.codeium/windsurf/mcp_config.json"',
    '      node -e "',
    "        const fs = require('fs');",
    "        const path = require('path');",
    '        const configPath = process.argv[1];',
    '        const serverName = process.argv[2];',
    '        const mcpUrl = process.argv[3];',
    '        const apiKey = process.argv[4];',
    '        let config = {};',
    "        try { config = JSON.parse(fs.readFileSync(configPath, 'utf8')); } catch {}",
    '        if (!config.mcpServers) config.mcpServers = {};',
    "        const server = { type: 'http', url: mcpUrl };",
    "        if (apiKey) server.headers = { Authorization: 'Bearer ' + apiKey };",
    '        config.mcpServers[serverName] = server;',
    '        fs.mkdirSync(path.dirname(configPath), { recursive: true });',
    '        fs.writeFileSync(configPath, JSON.stringify(config, null, 2));',
    '      " "$CONFIG_PATH" "$SERVER_NAME" "$MCP_URL" "$API_KEY" && {',
    '        success "$NAME -> Windsurf"',
    '        CONFIGURED=$((CONFIGURED + 1))',
    '      } || {',
    '        warn "Failed to configure $NAME for Windsurf"',
    '        FAILED=$((FAILED + 1))',
    '      }',
    '      ;;',
    '',
    '    claude-desktop)',
    '      if [ "$(uname)" = "Darwin" ]; then',
    '        CONFIG_PATH="$HOME/Library/Application Support/Claude/claude_desktop_config.json"',
    '      elif [ -n "${APPDATA:-}" ]; then',
    '        CONFIG_PATH="$APPDATA/Claude/claude_desktop_config.json"',
    '      else',
    '        CONFIG_PATH="$HOME/.config/Claude/claude_desktop_config.json"',
    '      fi',
    '',
    '      node -e "',
    "        const fs = require('fs');",
    "        const path = require('path');",
    '        const configPath = process.argv[1];',
    '        const serverName = process.argv[2];',
    '        const mcpUrl = process.argv[3];',
    '        const apiKey = process.argv[4];',
    '        let config = {};',
    "        try { config = JSON.parse(fs.readFileSync(configPath, 'utf8')); } catch {}",
    '        if (!config.mcpServers) config.mcpServers = {};',
    "        const server = { type: 'http', url: mcpUrl };",
    "        if (apiKey) server.headers = { Authorization: 'Bearer ' + apiKey };",
    '        config.mcpServers[serverName] = server;',
    '        fs.mkdirSync(path.dirname(configPath), { recursive: true });',
    '        fs.writeFileSync(configPath, JSON.stringify(config, null, 2));',
    '      " "$CONFIG_PATH" "$SERVER_NAME" "$MCP_URL" "$API_KEY" && {',
    '        success "$NAME -> Claude Desktop"',
    '        CONFIGURED=$((CONFIGURED + 1))',
    '      } || {',
    '        warn "Failed to configure $NAME for Claude Desktop"',
    '        FAILED=$((FAILED + 1))',
    '      }',
    '      ;;',
    '',
    '    *)',
    '      warn "Unknown editor: $EDITOR. Skipping $NAME."',
    '      FAILED=$((FAILED + 1))',
    '      ;;',
    '  esac',
    'done',
    '',
    '# Summary',
    'printf "\\n"',
    'printf "%s── Summary ─────────────────────────────────────%s\\n" "$BOLD" "$NC"',
    '',
    'if [ "$CONFIGURED" -gt 0 ]; then',
    '  success "${CONFIGURED} MCP server(s) configured successfully."',
    'fi',
    '',
    'if [ "$FAILED" -gt 0 ]; then',
    '  warn "${FAILED} configuration(s) skipped or failed."',
    'fi',
    '',
    'printf "\\n"',
    'printf "  Your MCP tools are ready. Restart your editor(s) to load them.\\n"',
    'printf "  Manage collections at %shttps://tpmjs.com/@%s%s\\n" "$BOLD" "$USERNAME" "$NC"',
    'printf "\\n"',
  ];

  const script = lines.join('\n') + '\n';

  return new Response(script, {
    headers: {
      'Content-Type': 'text/plain; charset=utf-8',
      'Cache-Control': 'no-cache',
    },
  });
}
