export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';
export const maxDuration = 60;

/**
 * GET /api/setup/install.sh
 *
 * Serves the TPMJS install script. Two modes:
 *   1. curl -fsSL https://tpmjs.com/install.sh | bash
 *      → Opens browser, polls for setup completion
 *   2. curl -fsSL https://tpmjs.com/install.sh | bash -s -- --token=<token>
 *      → Direct token redemption (skip browser)
 *
 * The script is idempotent — safe to run multiple times. It detects existing
 * configs and reports whether each server was added, updated, or already up to date.
 */
export async function GET() {
  // Using an array of lines to avoid template literal escaping issues with bash $ variables
  const lines = [
    '#!/bin/bash',
    'set -euo pipefail',
    '',
    '# Colors',
    "RED=$'\\033[0;31m'",
    "GREEN=$'\\033[0;32m'",
    "YELLOW=$'\\033[1;33m'",
    "BLUE=$'\\033[0;34m'",
    "CYAN=$'\\033[0;36m'",
    "DIM=$'\\033[2m'",
    "BOLD=$'\\033[1m'",
    "NC=$'\\033[0m'",
    '',
    'info()    { printf "%s[info]%s  %s\\n" "$BLUE" "$NC" "$1"; }',
    'success() { printf "%s[ok]%s    %s\\n" "$GREEN" "$NC" "$1"; }',
    'warn()    { printf "%s[warn]%s  %s\\n" "$YELLOW" "$NC" "$1"; }',
    'fail()    { printf "%s[error]%s %s\\n" "$RED" "$NC" "$1"; }',
    'dim()     { printf "%s%s%s\\n" "$DIM" "$1" "$NC"; }',
    '',
    '# Banner',
    'printf "\\n%s%s" "$BOLD" "$CYAN"',
    'printf "  _____ ____  __  __     _ ____  \\n"',
    'printf " |_   _|  _ \\\\|  \\\\/  |   | / ___| \\n"',
    'printf "   | | | |_) | |\\\\/| |_  | \\\\___ \\\\ \\n"',
    'printf "   | | |  __/| |  | | |_| |___) |\\n"',
    'printf "   |_| |_|   |_|  |_|\\\\___/|____/ \\n"',
    'printf "\\n"',
    'printf "  MCP Server Setup%s\\n\\n" "$NC"',
    '',
    '# Pre-flight checks',
    'if ! command -v curl &>/dev/null; then',
    '  fail "curl is required but not installed."',
    '  exit 1',
    'fi',
    '',
    'if ! command -v node &>/dev/null; then',
    '  fail "Node.js is required but not installed."',
    '  printf "  Install it from https://nodejs.org\\n"',
    '  exit 1',
    'fi',
    '',
    '# Parse arguments',
    'TOKEN=""',
    'for arg in "$@"; do',
    '  case "$arg" in',
    '    --token=*)',
    '      TOKEN="${arg#--token=}"',
    '      ;;',
    '  esac',
    'done',
    '',
    '# ---- Open browser flow (no token) ----------------------------------------',
    '',
    'if [ -z "$TOKEN" ]; then',
    '  info "Opening your browser to configure TPMJS..."',
    '  printf "\\n"',
    '',
    '  CLAIM_RESPONSE=$(curl -fsSL -X POST "https://tpmjs.com/api/setup/claim" 2>&1) || {',
    '    fail "Failed to connect to tpmjs.com"',
    '    printf "\\n  Check your internet connection and try again.\\n"',
    '    exit 1',
    '  }',
    '',
    '  CLAIM_CODE=$(node -e "console.log(JSON.parse(process.argv[1]).claimCode)" "$CLAIM_RESPONSE" 2>/dev/null) || {',
    '    fail "Unexpected response from server"',
    '    printf "\\n  Try again in a moment. If it persists, visit https://tpmjs.com/setup\\n"',
    '    exit 1',
    '  }',
    '',
    '  SETUP_URL="https://tpmjs.com/setup?claim=${CLAIM_CODE}"',
    '',
    '  # Open browser',
    '  OPENED_BROWSER=false',
    '  if command -v open &>/dev/null; then',
    '    open "$SETUP_URL" && OPENED_BROWSER=true',
    '  elif command -v xdg-open &>/dev/null; then',
    '    xdg-open "$SETUP_URL" && OPENED_BROWSER=true',
    '  elif command -v wslview &>/dev/null; then',
    '    wslview "$SETUP_URL" && OPENED_BROWSER=true',
    '  fi',
    '',
    '  if [ "$OPENED_BROWSER" = true ]; then',
    '    info "Browser opened. Complete setup there and come back here."',
    '  else',
    '    printf "  Open this URL in your browser:\\n"',
    '    printf "  %s%s%s\\n" "$BOLD" "$SETUP_URL" "$NC"',
    '  fi',
    '',
    '  printf "\\n"',
    '  printf "  %s1.%s Sign in (or create an account)\\n" "$CYAN" "$NC"',
    '  printf "  %s2.%s Select which collections to connect\\n" "$CYAN" "$NC"',
    '  printf "  %s3.%s Pick an editor for each collection\\n" "$CYAN" "$NC"',
    '  printf "  %s4.%s Click %sGenerate Install Command%s\\n" "$CYAN" "$NC" "$BOLD" "$NC"',
    '  printf "\\n"',
    '  info "Waiting for you to complete setup in the browser..."',
    '  dim "  (This will wait up to 5 minutes, then timeout. You can always re-run this script.)"',
    '',
    '  # Poll for completion (5 min timeout, 2 sec interval)',
    '  TIMEOUT=300',
    '  ELAPSED=0',
    '  POLL_DATA=""',
    '',
    '  while [ "$ELAPSED" -lt "$TIMEOUT" ]; do',
    '    POLL_RESPONSE=$(curl -fsSL "https://tpmjs.com/api/setup/poll/${CLAIM_CODE}" 2>/dev/null) || true',
    '',
    '    POLL_STATUS=$(node -e "',
    '      try {',
    '        const d = JSON.parse(process.argv[1]);',
    "        console.log(d.status || 'error');",
    "      } catch { console.log('error'); }",
    '    " "$POLL_RESPONSE" 2>/dev/null) || POLL_STATUS="error"',
    '',
    '    if [ "$POLL_STATUS" = "ready" ]; then',
    '      POLL_DATA="$POLL_RESPONSE"',
    '      break',
    '    fi',
    '',
    '    if [ "$POLL_STATUS" = "error" ]; then',
    '      ERROR_MSG=$(node -e "',
    "        try { console.log(JSON.parse(process.argv[1]).error || 'Unknown error'); }",
    "        catch { console.log('Unknown error'); }",
    '      " "$POLL_RESPONSE" 2>/dev/null) || ERROR_MSG="Unknown error"',
    '      fail "$ERROR_MSG"',
    '      printf "\\n  Run this script again to start over.\\n"',
    '      exit 1',
    '    fi',
    '',
    '    sleep 2',
    '    ELAPSED=$((ELAPSED + 2))',
    '',
    '    if [ $((ELAPSED % 30)) -eq 0 ]; then',
    '      printf "  %s...still waiting (%ss)%s\\n" "$DIM" "$ELAPSED" "$NC"',
    '    fi',
    '  done',
    '',
    '  if [ -z "$POLL_DATA" ]; then',
    '    fail "Timed out waiting for setup (5 minutes)."',
    '    printf "\\n  No worries — just run this command again to start over:\\n"',
    '    printf "  %scurl -fsSL https://tpmjs.com/install.sh | bash%s\\n\\n" "$BOLD" "$NC"',
    '    exit 1',
    '  fi',
    '',
    '  printf "\\n"',
    '  success "Configuration received!"',
    '  printf "\\n"',
    '',
    '  USERNAME=$(node -e "console.log(JSON.parse(process.argv[1]).username)" "$POLL_DATA")',
    '  API_KEY=$(node -e "const d=JSON.parse(process.argv[1]); console.log(d.apiKey||\'\')" "$POLL_DATA")',
    '  MAPPING_COUNT=$(node -e "console.log(JSON.parse(process.argv[1]).mappings.length)" "$POLL_DATA")',
    '  PARSED="$POLL_DATA"',
    '',
    'else',
    '  # ---- Direct token flow ---------------------------------------------------',
    '  info "Redeeming setup token..."',
    '',
    '  RESPONSE=$(curl -fsSL "https://tpmjs.com/api/setup/redeem/$TOKEN" 2>&1) || {',
    '    fail "Failed to redeem token."',
    '    printf "\\n  The token may be expired or already used.\\n"',
    '    printf "  Run this to start fresh:\\n"',
    '    printf "  %scurl -fsSL https://tpmjs.com/install.sh | bash%s\\n\\n" "$BOLD" "$NC"',
    '    exit 1',
    '  }',
    '',
    '  node -e "',
    '    const data = JSON.parse(process.argv[1]);',
    '    if (!data.success) {',
    "      console.error(data.error || 'Unknown error');",
    '      process.exit(1);',
    '    }',
    '  " "$RESPONSE" 2>&1 || {',
    '    fail "Invalid server response."',
    '    printf "\\n  Run this to start fresh:\\n"',
    '    printf "  %scurl -fsSL https://tpmjs.com/install.sh | bash%s\\n\\n" "$BOLD" "$NC"',
    '    exit 1',
    '  }',
    '',
    '  PARSED="$RESPONSE"',
    '  USERNAME=$(node -e "console.log(JSON.parse(process.argv[1]).username)" "$PARSED")',
    '  API_KEY=$(node -e "const d=JSON.parse(process.argv[1]); console.log(d.apiKey||\'\')" "$PARSED")',
    '  MAPPING_COUNT=$(node -e "console.log(JSON.parse(process.argv[1]).mappings.length)" "$PARSED")',
    'fi',
    '',
    'success "Authenticated as ${BOLD}${USERNAME}${NC}"',
    '',
    'if [ -n "$API_KEY" ]; then',
    '  info "API key: ${API_KEY:0:20}..."',
    'fi',
    '',
    'printf "\\n"',
    '',
    '# ---- Configure editors ----------------------------------------------------',
    '# Track outcomes: added (new), updated (existed but changed), unchanged, failed',
    '',
    'ADDED=0',
    'UPDATED=0',
    'UNCHANGED=0',
    'FAILED=0',
    '',
    '# Build server JSON for standard MCP format (most editors)',
    'build_standard_json() {',
    '  node -e "',
    "    const config = { type: 'http', url: process.argv[1] };",
    "    if (process.argv[2]) config.headers = { Authorization: 'Bearer ' + process.argv[2] };",
    '    console.log(JSON.stringify(config));',
    '  " "$1" "$2"',
    '}',
    '',
    '# Build server JSON for VS Code format (uses requestInit.headers)',
    'build_vscode_json() {',
    '  node -e "',
    "    const config = { type: 'http', url: process.argv[1] };",
    "    if (process.argv[2]) config.requestInit = { headers: { Authorization: 'Bearer ' + process.argv[2] } };",
    '    console.log(JSON.stringify(config));',
    '  " "$1" "$2"',
    '}',
    '',
    '# Helper: configure a JSON-based editor',
    '# Args: configPath serverName serverJson wrapperKey',
    '# Exits 0=added, 1=error, 2=updated, 3=unchanged',
    'configure_json_editor() {',
    '  node -e "',
    "    const fs = require('fs');",
    "    const path = require('path');",
    '    const configPath = process.argv[1];',
    '    const serverName = process.argv[2];',
    '    const serverJson = JSON.parse(process.argv[3]);',
    '    const wrapperKey = process.argv[4];',
    '',
    '    let config = {};',
    "    try { config = JSON.parse(fs.readFileSync(configPath, 'utf8')); } catch {}",
    '    if (!config[wrapperKey]) config[wrapperKey] = {};',
    '',
    '    const existing = config[wrapperKey][serverName];',
    '    if (existing) {',
    '      if (JSON.stringify(existing) === JSON.stringify(serverJson)) {',
    '        process.exit(3);',
    '      }',
    '      config[wrapperKey][serverName] = serverJson;',
    '      fs.mkdirSync(path.dirname(configPath), { recursive: true });',
    '      fs.writeFileSync(configPath, JSON.stringify(config, null, 2));',
    '      process.exit(2);',
    '    }',
    '',
    '    config[wrapperKey][serverName] = serverJson;',
    '    fs.mkdirSync(path.dirname(configPath), { recursive: true });',
    '    fs.writeFileSync(configPath, JSON.stringify(config, null, 2));',
    '    process.exit(0);',
    '  " "$@"',
    '}',
    '',
    '# Helper: report result from a JSON editor configure',
    'report_json_result() {',
    '  local exit_code=$1',
    '  local name=$2',
    '  local editor_label=$3',
    '',
    '  case $exit_code in',
    '    0)',
    '      success "$name -> $editor_label ${DIM}(added)${NC}"',
    '      ADDED=$((ADDED + 1))',
    '      ;;',
    '    2)',
    '      success "$name -> $editor_label ${DIM}(updated)${NC}"',
    '      UPDATED=$((UPDATED + 1))',
    '      ;;',
    '    3)',
    '      success "$name -> $editor_label ${DIM}(already up to date)${NC}"',
    '      UNCHANGED=$((UNCHANGED + 1))',
    '      ;;',
    '    *)',
    '      warn "Failed to configure $name for $editor_label"',
    '      FAILED=$((FAILED + 1))',
    '      ;;',
    '  esac',
    '}',
    '',
    'for i in $(seq 0 $((MAPPING_COUNT - 1))); do',
    '  SLUG=$(node -e "console.log(JSON.parse(process.argv[1]).mappings[$i].collectionSlug)" "$PARSED")',
    '  NAME=$(node -e "console.log(JSON.parse(process.argv[1]).mappings[$i].collectionName)" "$PARSED")',
    '  EDITOR=$(node -e "console.log(JSON.parse(process.argv[1]).mappings[$i].editor)" "$PARSED")',
    '  MCP_URL=$(node -e "console.log(JSON.parse(process.argv[1]).mappings[$i].mcpUrl)" "$PARSED")',
    '  SERVER_NAME="tpmjs-$SLUG"',
    '',
    '  case "$EDITOR" in',
    '',
    '    claude-code)',
    '      if ! command -v claude &>/dev/null; then',
    '        warn "$NAME -> Claude Code ${DIM}(skipped: claude CLI not found)${NC}"',
    '        dim "         Install: npm install -g @anthropic-ai/claude-code"',
    '        FAILED=$((FAILED + 1))',
    '        continue',
    '      fi',
    '',
    '      MCP_JSON=$(build_standard_json "$MCP_URL" "$API_KEY")',
    '      EXISTING=$(claude mcp get-json "$SERVER_NAME" 2>/dev/null || true)',
    '',
    '      if [ -n "$EXISTING" ] && [ "$EXISTING" = "$MCP_JSON" ]; then',
    '        success "$NAME -> Claude Code ${DIM}(already up to date)${NC}"',
    '        UNCHANGED=$((UNCHANGED + 1))',
    '      elif [ -n "$EXISTING" ]; then',
    '        if claude mcp add-json "$SERVER_NAME" "$MCP_JSON" 2>/dev/null; then',
    '          success "$NAME -> Claude Code ${DIM}(updated)${NC}"',
    '          UPDATED=$((UPDATED + 1))',
    '        else',
    '          warn "$NAME -> Claude Code ${DIM}(update failed)${NC}"',
    '          FAILED=$((FAILED + 1))',
    '        fi',
    '      else',
    '        if claude mcp add-json "$SERVER_NAME" "$MCP_JSON" 2>/dev/null; then',
    '          success "$NAME -> Claude Code ${DIM}(added)${NC}"',
    '          ADDED=$((ADDED + 1))',
    '        else',
    '          warn "$NAME -> Claude Code ${DIM}(failed)${NC}"',
    '          FAILED=$((FAILED + 1))',
    '        fi',
    '      fi',
    '      ;;',
    '',
    '    vscode)',
    '      if [ "$(uname)" = "Darwin" ]; then',
    '        CONFIG_PATH="$HOME/Library/Application Support/Code/User/mcp.json"',
    '      else',
    '        CONFIG_PATH="$HOME/.config/Code/User/mcp.json"',
    '      fi',
    '      SERVER_JSON=$(build_vscode_json "$MCP_URL" "$API_KEY")',
    '      JSON_RC=0',
    '      configure_json_editor "$CONFIG_PATH" "$SERVER_NAME" "$SERVER_JSON" "servers" || JSON_RC=$?',
    '      report_json_result "$JSON_RC" "$NAME" "VS Code"',
    '      ;;',
    '',
    '    cursor)',
    '      CONFIG_PATH="$HOME/.cursor/mcp.json"',
    '      SERVER_JSON=$(build_standard_json "$MCP_URL" "$API_KEY")',
    '      JSON_RC=0',
    '      configure_json_editor "$CONFIG_PATH" "$SERVER_NAME" "$SERVER_JSON" "mcpServers" || JSON_RC=$?',
    '      report_json_result "$JSON_RC" "$NAME" "Cursor"',
    '      ;;',
    '',
    '    windsurf)',
    '      CONFIG_PATH="$HOME/.codeium/windsurf/mcp_config.json"',
    '      SERVER_JSON=$(build_standard_json "$MCP_URL" "$API_KEY")',
    '      JSON_RC=0',
    '      configure_json_editor "$CONFIG_PATH" "$SERVER_NAME" "$SERVER_JSON" "mcpServers" || JSON_RC=$?',
    '      report_json_result "$JSON_RC" "$NAME" "Windsurf"',
    '      ;;',
    '',
    '    claude-desktop)',
    '      if [ "$(uname)" = "Darwin" ]; then',
    '        CONFIG_PATH="$HOME/Library/Application Support/Claude/claude_desktop_config.json"',
    '      elif [ -n "${APPDATA:-}" ]; then',
    '        CONFIG_PATH="$APPDATA/Claude/claude_desktop_config.json"',
    '      else',
    '        CONFIG_PATH="$HOME/.config/Claude/claude_desktop_config.json"',
    '      fi',
    '      SERVER_JSON=$(build_standard_json "$MCP_URL" "$API_KEY")',
    '      JSON_RC=0',
    '      configure_json_editor "$CONFIG_PATH" "$SERVER_NAME" "$SERVER_JSON" "mcpServers" || JSON_RC=$?',
    '      report_json_result "$JSON_RC" "$NAME" "Claude Desktop"',
    '      ;;',
    '',
    '    codex)',
    '      CONFIG_PATH="$HOME/.codex/config.toml"',
    '      mkdir -p "$HOME/.codex"',
    '',
    '      # Codex uses TOML — handle add, update, and unchanged',
    '      CODEX_RESULT=$(node -e "',
    "        const fs = require('fs');",
    '        const configPath = process.argv[1];',
    '        const serverName = process.argv[2];',
    '        const mcpUrl = process.argv[3];',
    '        const apiKey = process.argv[4];',
    '',
    "        let content = '';",
    "        try { content = fs.readFileSync(configPath, 'utf8'); } catch {}",
    '',
    "        const tomlName = serverName.replace(/-/g, '_');",
    "        const header = '[mcp_servers.' + tomlName + ']';",
    '',
    '        // Build the new section',
    '        const q = String.fromCharCode(34);',
    "        let newLines = [header, 'url = ' + q + mcpUrl + q];",
    '        if (apiKey) {',
    "          newLines.push('http_headers = { ' + q + 'Authorization' + q + ' = ' + q + 'Bearer ' + apiKey + q + ' }');",
    '        }',
    "        const newSection = newLines.join('\\n');",
    '',
    '        if (content.includes(header)) {',
    '          // Extract existing section (from header to next section or end of file)',
    "          const lines = content.split('\\n');",
    '          let sectionStart = -1;',
    '          let sectionEnd = lines.length;',
    '          for (let j = 0; j < lines.length; j++) {',
    '            if (lines[j].trim() === header) {',
    '              sectionStart = j;',
    "            } else if (sectionStart >= 0 && lines[j].startsWith('[') && j > sectionStart) {",
    '              sectionEnd = j;',
    '              break;',
    '            }',
    '          }',
    '',
    '          // Remove trailing blank lines from existing section',
    "          while (sectionEnd > sectionStart + 1 && lines[sectionEnd - 1].trim() === '') {",
    '            sectionEnd--;',
    '          }',
    "          const existingSection = lines.slice(sectionStart, sectionEnd).join('\\n');",
    '',
    '          if (existingSection === newSection) {',
    "            console.log('unchanged');",
    '          } else {',
    '            // Replace the old section',
    '            lines.splice(sectionStart, sectionEnd - sectionStart, ...newLines);',
    "            fs.writeFileSync(configPath, lines.join('\\n'));",
    "            console.log('updated');",
    '          }',
    '        } else {',
    '          // Append new section',
    "          const separator = content.length > 0 && !content.endsWith('\\n\\n') ? '\\n' : '';",
    "          content += separator + newSection + '\\n';",
    '          fs.writeFileSync(configPath, content);',
    "          console.log('added');",
    '        }',
    '      " "$CONFIG_PATH" "$SERVER_NAME" "$MCP_URL" "$API_KEY" 2>/dev/null) || CODEX_RESULT="error"',
    '',
    '      case "$CODEX_RESULT" in',
    '        added)',
    '          success "$NAME -> Codex ${DIM}(added)${NC}"',
    '          ADDED=$((ADDED + 1))',
    '          ;;',
    '        updated)',
    '          success "$NAME -> Codex ${DIM}(updated)${NC}"',
    '          UPDATED=$((UPDATED + 1))',
    '          ;;',
    '        unchanged)',
    '          success "$NAME -> Codex ${DIM}(already up to date)${NC}"',
    '          UNCHANGED=$((UNCHANGED + 1))',
    '          ;;',
    '        *)',
    '          warn "$NAME -> Codex ${DIM}(failed)${NC}"',
    '          FAILED=$((FAILED + 1))',
    '          ;;',
    '      esac',
    '      ;;',
    '',
    '    gemini-cli)',
    '      CONFIG_PATH="$HOME/.gemini/settings.json"',
    '      SERVER_JSON=$(build_standard_json "$MCP_URL" "$API_KEY")',
    '      JSON_RC=0',
    '      configure_json_editor "$CONFIG_PATH" "$SERVER_NAME" "$SERVER_JSON" "mcpServers" || JSON_RC=$?',
    '      report_json_result "$JSON_RC" "$NAME" "Gemini CLI"',
    '      ;;',
    '',
    '    copilot-cli)',
    '      CONFIG_PATH="$HOME/.copilot/mcp-config.json"',
    '      SERVER_JSON=$(build_standard_json "$MCP_URL" "$API_KEY")',
    '      JSON_RC=0',
    '      configure_json_editor "$CONFIG_PATH" "$SERVER_NAME" "$SERVER_JSON" "mcpServers" || JSON_RC=$?',
    '      report_json_result "$JSON_RC" "$NAME" "Copilot CLI"',
    '      ;;',
    '',
    '    amazon-q)',
    '      CONFIG_PATH="$HOME/.aws/amazonq/default.json"',
    '      SERVER_JSON=$(build_standard_json "$MCP_URL" "$API_KEY")',
    '      JSON_RC=0',
    '      configure_json_editor "$CONFIG_PATH" "$SERVER_NAME" "$SERVER_JSON" "mcpServers" || JSON_RC=$?',
    '      report_json_result "$JSON_RC" "$NAME" "Amazon Q"',
    '      ;;',
    '',
    '    cline)',
    '      if [ "$(uname)" = "Darwin" ]; then',
    '        CONFIG_PATH="$HOME/Library/Application Support/Code/User/globalStorage/saoudrizwan.claude-dev/settings/cline_mcp_settings.json"',
    '      else',
    '        CONFIG_PATH="$HOME/.config/Code/User/globalStorage/saoudrizwan.claude-dev/settings/cline_mcp_settings.json"',
    '      fi',
    '      SERVER_JSON=$(build_standard_json "$MCP_URL" "$API_KEY")',
    '      JSON_RC=0',
    '      configure_json_editor "$CONFIG_PATH" "$SERVER_NAME" "$SERVER_JSON" "mcpServers" || JSON_RC=$?',
    '      report_json_result "$JSON_RC" "$NAME" "Cline"',
    '      ;;',
    '',
    '    continue)',
    '      CONFIG_PATH="$HOME/.continue/config.json"',
    '      SERVER_JSON=$(build_standard_json "$MCP_URL" "$API_KEY")',
    '      JSON_RC=0',
    '      configure_json_editor "$CONFIG_PATH" "$SERVER_NAME" "$SERVER_JSON" "mcpServers" || JSON_RC=$?',
    '      report_json_result "$JSON_RC" "$NAME" "Continue"',
    '      ;;',
    '',
    '    tabnine)',
    '      CONFIG_PATH="$HOME/.tabnine/mcp_servers.json"',
    '      SERVER_JSON=$(build_standard_json "$MCP_URL" "$API_KEY")',
    '      JSON_RC=0',
    '      configure_json_editor "$CONFIG_PATH" "$SERVER_NAME" "$SERVER_JSON" "mcpServers" || JSON_RC=$?',
    '      report_json_result "$JSON_RC" "$NAME" "Tabnine"',
    '      ;;',
    '',
    '    augment)',
    '      CONFIG_PATH="$HOME/.augment/settings.json"',
    '      SERVER_JSON=$(build_standard_json "$MCP_URL" "$API_KEY")',
    '      JSON_RC=0',
    '      configure_json_editor "$CONFIG_PATH" "$SERVER_NAME" "$SERVER_JSON" "mcpServers" || JSON_RC=$?',
    '      report_json_result "$JSON_RC" "$NAME" "Augment"',
    '      ;;',
    '',
    '    *)',
    '      warn "$NAME -> $EDITOR ${DIM}(unknown editor, skipped)${NC}"',
    '      FAILED=$((FAILED + 1))',
    '      ;;',
    '  esac',
    'done',
    '',
    '# ---- Summary ---------------------------------------------------------------',
    'printf "\\n"',
    'printf "%s── Summary ─────────────────────────────────────%s\\n" "$BOLD" "$NC"',
    'printf "\\n"',
    '',
    'TOTAL=$((ADDED + UPDATED + UNCHANGED))',
    '',
    'if [ "$ADDED" -gt 0 ]; then',
    '  success "${ADDED} server(s) added"',
    'fi',
    '',
    'if [ "$UPDATED" -gt 0 ]; then',
    '  success "${UPDATED} server(s) updated"',
    'fi',
    '',
    'if [ "$UNCHANGED" -gt 0 ]; then',
    '  info "${UNCHANGED} server(s) already up to date"',
    'fi',
    '',
    'if [ "$FAILED" -gt 0 ]; then',
    '  warn "${FAILED} server(s) skipped or failed"',
    'fi',
    '',
    'printf "\\n"',
    '',
    'if [ "$TOTAL" -gt 0 ]; then',
    '  if [ "$ADDED" -gt 0 ] || [ "$UPDATED" -gt 0 ]; then',
    '    printf "  Restart your editor(s) to load the new configuration.\\n"',
    '  else',
    '    printf "  Everything is already configured. No changes needed.\\n"',
    '  fi',
    'fi',
    '',
    'if [ "$FAILED" -gt 0 ] && [ "$TOTAL" -eq 0 ]; then',
    '  printf "  Nothing was configured. Fix the issues above and re-run:\\n"',
    '  printf "  %scurl -fsSL https://tpmjs.com/install.sh | bash%s\\n" "$BOLD" "$NC"',
    'fi',
    '',
    'printf "  Manage collections at %shttps://tpmjs.com/@%s%s\\n" "$BOLD" "$USERNAME" "$NC"',
    'printf "\\n"',
    'dim "  This script is safe to run again anytime — it will only update what changed."',
    'printf "\\n"',
  ];

  const script = `${lines.join('\n')}\n`;

  return new Response(script, {
    headers: {
      'Content-Type': 'text/plain; charset=utf-8',
      'Cache-Control': 'no-cache',
    },
  });
}
