#!/usr/bin/env node
// Regenerates src/catalog.ts, src/index.ts and the `tpmjs.tools` list in package.json
// from HAM's own MCP tool catalog, so this package never hand-maintains tool schemas.
//
//   node scripts/generate.mjs                # uses scripts/catalog.json (committed snapshot)
//   HAM_API_URL=https://ham.donto.org HAM_API_KEY=... node scripts/generate.mjs --fetch
//                                            # refreshes the snapshot from a live HAM first
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..');
const snapshotPath = join(here, 'catalog.json');

async function fetchCatalog() {
  const base = (process.env.HAM_API_URL || 'https://ham.donto.org').replace(/\/$/, '');
  const key = process.env.HAM_API_KEY;
  if (!key) throw new Error('HAM_API_KEY is required with --fetch');
  const res = await fetch(`${base}/mcp`, {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${key}`,
      'Content-Type': 'application/json',
      Accept: 'application/json, text/event-stream',
    },
    body: JSON.stringify({ jsonrpc: '2.0', id: 1, method: 'tools/list', params: {} }),
  });
  const raw = await res.text();
  const data = raw
    .split('\n')
    .filter((l) => l.startsWith('data:'))
    .map((l) => l.slice(5).trim())
    .join('\n');
  const parsed = JSON.parse(data || raw);
  if (parsed.error) throw new Error(`HAM tools/list failed: ${JSON.stringify(parsed.error)}`);
  return parsed.result.tools.map((t) => ({
    name: t.name,
    description: t.description,
    inputSchema: t.inputSchema,
  }));
}

/** ham_recall_deep -> recallDeep (deterministic, no lookup table) */
function exportName(hamName) {
  const stripped = hamName.replace(/^ham_/, '');
  return stripped.replace(/_([a-z0-9])/g, (_, c) => c.toUpperCase());
}

function clampDescription(text, fallback) {
  let d = (text || '').replace(/\s+/g, ' ').trim();
  if (d.length < 20) d = `${d} ${fallback}`.trim();
  if (d.length > 500) d = `${d.slice(0, 497)}...`;
  return d;
}

const catalog = process.argv.includes('--fetch')
  ? await fetchCatalog()
  : JSON.parse(readFileSync(snapshotPath, 'utf8'));
catalog.sort((a, b) => a.name.localeCompare(b.name));
if (process.argv.includes('--fetch'))
  writeFileSync(snapshotPath, `${JSON.stringify(catalog, null, 2)}\n`);

// src/catalog.ts — the schemas as data
const catalogTs = [
  "// GENERATED by scripts/generate.mjs from HAM's MCP tool catalog — do not edit by hand.",
  "import type { JSONSchema7 } from 'ai';",
  '',
  'export interface HamToolSpec {',
  '  /** Canonical HAM MCP tool name, e.g. "ham_remember" */',
  '  name: string;',
  '  description: string;',
  '  inputSchema: JSONSchema7;',
  '}',
  '',
  `export const HAM_TOOL_CATALOG: readonly HamToolSpec[] = ${JSON.stringify(catalog, null, 2)} as const;`,
  '',
]
  .join('\n')
  // JSON Schema's conditional keywords (if/then/else) are data here, not thenables.
  .replace(
    /^(\s*)"then": \{/gm,
    '$1// biome-ignore lint/suspicious/noThenProperty: JSON Schema conditional keyword\n$1then: {'
  );
writeFileSync(join(root, 'src', 'catalog.ts'), catalogTs);

// src/index.ts — one named export per HAM tool
const lines = [
  '/**',
  ' * @tpmjs/tools-ham — HAM (shared agent memory) tools for AI agents.',
  ' *',
  ' * Every export forwards to the `ham_*` MCP tool of the same name on a HAM instance',
  ' * (https://github.com/MonumentalSystems/ham) over its authenticated Streamable-HTTP',
  ' * endpoint. Credentials come from the environment, so a tpmjs collection owner injects',
  ' * them as collection env vars and everyone else brings their own HAM key.',
  ' *',
  ' * @requires HAM_API_KEY environment variable (a HAM per-agent credential)',
  ' * @env HAM_API_URL optional HAM base URL (default https://ham.donto.org)',
  ' *',
  ' * GENERATED by scripts/generate.mjs — regenerate after a HAM upgrade changes the catalog.',
  ' */',
  '',
  "import { hamTool } from './client';",
  '',
  "export type { HamToolSpec } from './catalog';",
  "export { HAM_TOOL_CATALOG } from './catalog';",
  "export { callHam, type HamCallResult } from './client';",
  '',
];
for (const t of catalog) {
  lines.push(`/** ${clampDescription(t.description, `HAM tool ${t.name}.`)} */`);
  lines.push(`export const ${exportName(t.name)} = hamTool('${t.name}');`);
  lines.push('');
}
writeFileSync(join(root, 'src', 'index.ts'), `${lines.join('\n')}`);

// package.json tpmjs.tools
const pkgPath = join(root, 'package.json');
const pkg = JSON.parse(readFileSync(pkgPath, 'utf8'));
pkg.tpmjs.tools = catalog.map((t) => ({
  name: exportName(t.name),
  description: clampDescription(t.description, `Calls the HAM ${t.name} tool.`),
}));
writeFileSync(pkgPath, `${JSON.stringify(pkg, null, 2)}\n`);
console.log(`generated ${catalog.length} tools`);
