/**
 * @tpmjs/tools-ham — HAM (shared agent memory) tools for AI agents.
 *
 * Every export forwards to the `ham_*` MCP tool of the same name on a HAM instance
 * (https://github.com/MonumentalSystems/ham) over its authenticated Streamable-HTTP
 * endpoint. Credentials come from the environment, so a tpmjs collection owner injects
 * them as collection env vars and everyone else brings their own HAM key.
 *
 * @requires HAM_API_KEY environment variable (a HAM per-agent credential)
 * @env HAM_API_URL optional HAM base URL (default https://ham.donto.org)
 *
 * GENERATED by scripts/generate.mjs — regenerate after a HAM upgrade changes the catalog.
 */

import { hamTool } from './client';

export type { HamToolSpec } from './catalog';
export { HAM_TOOL_CATALOG } from './catalog';
export { callHam, type HamCallResult } from './client';

/** Send a directed asynchronous question to another agent without adding it to recall memory. */
export const ask = hamTool('ham_ask');

/** Catch up on memories created, superseded, retracted, or resolved since a cursor. */
export const changes = hamTool('ham_changes');

/** Record that this agent picked up an active handoff without adding a recall memory. */
export const claimHandoff = hamTool('ham_claim_handoff');

/** Mark a claimed handoff complete using its current receipt version. */
export const completeHandoff = hamTool('ham_complete_handoff');

/** Load relevant background context for a topic. Use at the start of a session to recall prior discussions. */
export const context = hamTool('ham_context');

/** Fetch a complete memory by ID, including provenance, state, and version. */
export const get = hamTool('ham_get');

/** Publish a structured handoff so another agent can continue the task with completed work, next steps, blockers, and files. */
export const handoff = hamTool('ham_handoff');

/** Check directed agent messages. Call at session start; open inbox items are returned by default. */
export const inbox = hamTool('ham_inbox');

/** Create one explicit HAM-controlled commitment and its durable GitHub mirror operation. */
export const issue = hamTool('ham_issue');

/** Explicitly keep HAM's canonical issue state after reviewing a GitHub-side conflict. */
export const issueResolveConflict = hamTool('ham_issue_resolve_conflict');

/** Resolve or reopen a tracked commitment with optimistic concurrency; the mirror converges durably. */
export const issueTransition = hamTool('ham_issue_transition');

/** Create an explicit typed relation from one memory to another. */
export const link = hamTool('ham_link');

/** List active typed relations connected to a memory. */
export const links = hamTool('ham_links');

/** Fetch one directed message by its deterministic ID, including reply and provenance. */
export const message = hamTool('ham_message');

/** List projects visible to the current credential, including canonical scope and repository. */
export const projects = hamTool('ham_projects');

/** Search shared memory with local learned semantics, harmonic resonance, and lexical matching. */
export const recall = hamTool('ham_recall');

/** Scoped semantic search followed by bounded cue, reference, and typed-link traversal with visible hop provenance. */
export const recallDeep = hamTool('ham_recall_deep');

/** Retrieve a deterministic chronological window around one scoped memory anchor. */
export const recallSequence = hamTool('ham_recall_sequence');

/** See recent shared work, decisions, blockers, and handoffs in the active project/repo/task context. */
export const recent = hamTool('ham_recent');

/** End-of-session reflection. Stores observations and runs durability-aware tier consolidation. */
export const reflect = hamTool('ham_reflect');

/** Store a memory in the Galaxy Brain knowledge base. Use this to save findings, decisions, observations, or any information worth remembering across sessions. */
export const remember = hamTool('ham_remember');

/** Answer an open directed message using optimistic concurrency. */
export const reply = hamTool('ham_reply');

/** List enrolled repositories visible to the current credential and their mirror state. */
export const repositories = hamTool('ham_repositories');

/** Run one bounded repository poll and durable reconciliation pass; read-only agents process only remote polling. */
export const repositorySync = hamTool('ham_repository_sync');

/** Retract an incorrect memory without deleting its audit history. */
export const retract = hamTool('ham_retract');

/** Read the latest concise exception review for one enrolled repository; reviews stay outside recall. */
export const review = hamTool('ham_review');

/** List current unresolved repository exceptions, including items omitted from unchanged reports. */
export const reviewCurrent = hamTool('ham_review_current');

/** Build a deterministic exception review for one enrolled repository; returns nothing noisy on a no-op when quiet_noop is true. */
export const reviewRun = hamTool('ham_review_run');

/** Close an unanswered directed message as stale while preserving its audit history. */
export const staleMessage = hamTool('ham_stale_message');

/** Get memory statistics -- tier distribution, total memories, total cue anchors. */
export const stats = hamTool('ham_stats');

/** Replace stale knowledge with a new immutable memory version using optimistic concurrency. */
export const supersede = hamTool('ham_supersede');

/** Accept a pending task with optimistic concurrency and a bounded lease; blocking resource conflicts require explicit acknowledgement. */
export const taskClaim = hamTool('ham_task_claim');

/** Fetch one visible task and its append-only lifecycle/progress history for durable multi-run context. */
export const taskGet = hamTool('ham_task_get');

/** Post an explicit unassigned project task with a visible goal, acceptance criteria, and declared resources. */
export const taskPost = hamTool('ham_task_post');

/** List visible project tasks with explicit goal, claimant, run progress, lease, and resource conflicts. */
export const taskQueue = hamTool('ham_task_queue');

/** Start or update an owned task run, record a queue response, or reconcile completion that occurred outside a tracked run without fabricating run provenance. */
export const taskUpdate = hamTool('ham_task_update');

/** Retract a typed memory relation without deleting its audit history. */
export const unlink = hamTool('ham_unlink');

/** Describe the current credential's identity, scope ceiling, visible projects, task access, and explicitly held and denied repository capabilities. Call at session start before selecting project, scope, or repository inputs. */
export const whoami = hamTool('ham_whoami');
