/**
 * Block metadata for Vercel tools
 * This file provides metadata for the blocks validator
 */
import {
  // Projects
  listProjects,
  createProject,
  getProject,
  updateProject,
  deleteProject,
  listProjectDomains,
  getProjectDomain,
  addProjectDomain,
  updateProjectDomain,
  removeProjectDomain,
  verifyProjectDomain,
  listProjectEnvVars,
  createProjectEnvVar,
  getProjectEnvVar,
  editProjectEnvVar,
  removeProjectEnvVar,
  pauseProject,
  unpauseProject,
  promoteDeployment,
  listPromoteAliases,
  updateProtectionBypass,
  // Deployments
  listDeployments,
  createDeployment,
  getDeployment,
  deleteDeployment,
  cancelDeployment,
  getDeploymentEvents,
  listDeploymentFiles,
  getDeploymentFile,
  // Domains
  listDomains,
  getDomain,
  addDomain,
  removeDomain,
  getDomainConfig,
  // DNS
  listDnsRecords,
  createDnsRecord,
  updateDnsRecord,
  deleteDnsRecord,
  // Domain Registrar
  checkDomainAvailability,
  getDomainPrice,
  buySingleDomain,
  // Teams
  listTeams,
  getTeam,
  createTeam,
  updateTeam,
  deleteTeam,
  listTeamMembers,
  inviteTeamMembers,
  updateTeamMember,
  removeTeamMember,
  joinTeam,
  requestTeamAccess,
  getAccessRequestStatus,
  deleteTeamInvite,
  // Access Groups
  listAccessGroups,
  createAccessGroup,
  getAccessGroup,
  updateAccessGroup,
  deleteAccessGroup,
  listAccessGroupMembers,
  listAccessGroupProjects,
  createAccessGroupProject,
  getAccessGroupProject,
  updateAccessGroupProject,
  deleteAccessGroupProject,
  // Edge Config
  listEdgeConfigs,
  createEdgeConfig,
  getEdgeConfig,
  updateEdgeConfig,
  deleteEdgeConfig,
  getEdgeConfigItems,
  getEdgeConfigItem,
  batchUpdateEdgeConfigItems,
  getEdgeConfigSchema,
  updateEdgeConfigSchema,
  deleteEdgeConfigSchema,
  createEdgeConfigToken,
  getEdgeConfigToken,
  listEdgeConfigTokens,
  deleteEdgeConfigTokens,
  listEdgeConfigBackups,
  getEdgeConfigBackup,
  // Environment Variables (Shared)
  createSharedEnvVar,
  listSharedEnvVars,
  updateSharedEnvVars,
  deleteSharedEnvVars,
  getSharedEnvVar,
  createCustomEnvironment,
  listCustomEnvironments,
  getCustomEnvironment,
  updateCustomEnvironment,
  removeCustomEnvironment,
  // Security / Firewall
  getAttackStatus,
  toggleAttackMode,
  getFirewallConfig,
  updateFirewallConfig,
  replaceFirewallConfig,
  listFirewallBypass,
  createFirewallBypass,
  deleteFirewallBypass,
  // Aliases
  listAliases,
  getAlias,
  deleteAlias,
  listDeploymentAliases,
  assignAlias,
  // Checks
  createCheck,
  listChecks,
  getCheck,
  updateCheck,
  rerequestCheck,
  // Webhooks
  createWebhook,
  listWebhooks,
  getWebhook,
  deleteWebhook,
  // Log Drains
  createDrain,
  listDrains,
  deleteDrain,
  // Certificates
  issueCertificate,
  uploadCertificate,
  getCertificate,
  deleteCertificate,
  // Artifacts / Remote Cache
  getArtifactStatus,
  uploadArtifact,
  downloadArtifact,
  checkArtifactExists,
  recordArtifactEvents,
  queryArtifacts,
  // Authentication
  listAuthTokens,
  getAuthToken,
  createAuthToken,
  deleteAuthToken,
  // User
  getAuthUser,
  deleteUser,
  listUserEvents,
  // Bulk Redirects
  stageRedirects,
  getRedirects,
  deleteRedirects,
  editRedirect,
  restoreRedirects,
  getRedirectVersions,
  promoteRedirectVersion,
  // Networks
  listNetworks,
  createNetwork,
  getNetwork,
  updateNetwork,
  deleteNetwork,
  // Rolling Release
  getRollingRelease,
  getRollingReleaseConfig,
  updateRollingReleaseConfig,
  deleteRollingReleaseConfig,
  approveRollingReleaseStage,
  completeRollingRelease,
  // Integrations
  listIntegrationConfigs,
  getIntegrationConfig,
  deleteIntegrationConfig,
  listGitNamespaces,
  searchGitRepo,
  // Project Members
  listProjectMembers,
  addProjectMember,
  removeProjectMember,
  // Log Drains - Legacy
  listLogDrains,
  createLogDrain,
  getLogDrain,
  deleteLogDrain,
  createIntegrationLogDrain,
  listIntegrationLogDrains,
  deleteIntegrationLogDrain,
} from './src/index.js';

export const block = {
  name: 'vercel',
  description:
    'Vercel platform API tools for AI agents. Manage projects, deployments, domains, DNS, teams, edge config, environment variables, and more.',
  tools: {
    // Projects (21)
    listProjects,
    createProject,
    getProject,
    updateProject,
    deleteProject,
    listProjectDomains,
    getProjectDomain,
    addProjectDomain,
    updateProjectDomain,
    removeProjectDomain,
    verifyProjectDomain,
    listProjectEnvVars,
    createProjectEnvVar,
    getProjectEnvVar,
    editProjectEnvVar,
    removeProjectEnvVar,
    pauseProject,
    unpauseProject,
    promoteDeployment,
    listPromoteAliases,
    updateProtectionBypass,
    // Deployments (8)
    listDeployments,
    createDeployment,
    getDeployment,
    deleteDeployment,
    cancelDeployment,
    getDeploymentEvents,
    listDeploymentFiles,
    getDeploymentFile,
    // Domains (5)
    listDomains,
    getDomain,
    addDomain,
    removeDomain,
    getDomainConfig,
    // DNS (4)
    listDnsRecords,
    createDnsRecord,
    updateDnsRecord,
    deleteDnsRecord,
    // Domain Registrar (3)
    checkDomainAvailability,
    getDomainPrice,
    buySingleDomain,
    // Teams (13)
    listTeams,
    getTeam,
    createTeam,
    updateTeam,
    deleteTeam,
    listTeamMembers,
    inviteTeamMembers,
    updateTeamMember,
    removeTeamMember,
    joinTeam,
    requestTeamAccess,
    getAccessRequestStatus,
    deleteTeamInvite,
    // Access Groups (11)
    listAccessGroups,
    createAccessGroup,
    getAccessGroup,
    updateAccessGroup,
    deleteAccessGroup,
    listAccessGroupMembers,
    listAccessGroupProjects,
    createAccessGroupProject,
    getAccessGroupProject,
    updateAccessGroupProject,
    deleteAccessGroupProject,
    // Edge Config (17)
    listEdgeConfigs,
    createEdgeConfig,
    getEdgeConfig,
    updateEdgeConfig,
    deleteEdgeConfig,
    getEdgeConfigItems,
    getEdgeConfigItem,
    batchUpdateEdgeConfigItems,
    getEdgeConfigSchema,
    updateEdgeConfigSchema,
    deleteEdgeConfigSchema,
    createEdgeConfigToken,
    getEdgeConfigToken,
    listEdgeConfigTokens,
    deleteEdgeConfigTokens,
    listEdgeConfigBackups,
    getEdgeConfigBackup,
    // Environment Variables (10)
    createSharedEnvVar,
    listSharedEnvVars,
    updateSharedEnvVars,
    deleteSharedEnvVars,
    getSharedEnvVar,
    createCustomEnvironment,
    listCustomEnvironments,
    getCustomEnvironment,
    updateCustomEnvironment,
    removeCustomEnvironment,
    // Security / Firewall (8)
    getAttackStatus,
    toggleAttackMode,
    getFirewallConfig,
    updateFirewallConfig,
    replaceFirewallConfig,
    listFirewallBypass,
    createFirewallBypass,
    deleteFirewallBypass,
    // Aliases (5)
    listAliases,
    getAlias,
    deleteAlias,
    listDeploymentAliases,
    assignAlias,
    // Checks (5)
    createCheck,
    listChecks,
    getCheck,
    updateCheck,
    rerequestCheck,
    // Webhooks (4)
    createWebhook,
    listWebhooks,
    getWebhook,
    deleteWebhook,
    // Log Drains (3)
    createDrain,
    listDrains,
    deleteDrain,
    // Certificates (4)
    issueCertificate,
    uploadCertificate,
    getCertificate,
    deleteCertificate,
    // Artifacts / Remote Cache (6)
    getArtifactStatus,
    uploadArtifact,
    downloadArtifact,
    checkArtifactExists,
    recordArtifactEvents,
    queryArtifacts,
    // Authentication (4)
    listAuthTokens,
    getAuthToken,
    createAuthToken,
    deleteAuthToken,
    // User (3)
    getAuthUser,
    deleteUser,
    listUserEvents,
    // Bulk Redirects (7)
    stageRedirects,
    getRedirects,
    deleteRedirects,
    editRedirect,
    restoreRedirects,
    getRedirectVersions,
    promoteRedirectVersion,
    // Networks (5)
    listNetworks,
    createNetwork,
    getNetwork,
    updateNetwork,
    deleteNetwork,
    // Rolling Release (6)
    getRollingRelease,
    getRollingReleaseConfig,
    updateRollingReleaseConfig,
    deleteRollingReleaseConfig,
    approveRollingReleaseStage,
    completeRollingRelease,
    // Integrations (5)
    listIntegrationConfigs,
    getIntegrationConfig,
    deleteIntegrationConfig,
    listGitNamespaces,
    searchGitRepo,
    // Project Members (3)
    listProjectMembers,
    addProjectMember,
    removeProjectMember,
    // Log Drains - Legacy (7)
    listLogDrains,
    createLogDrain,
    getLogDrain,
    deleteLogDrain,
    createIntegrationLogDrain,
    listIntegrationLogDrains,
    deleteIntegrationLogDrain,
  },
};

export default block;
